# 神经网络 neural network

In [8]:
from torch import nn


class MyModule(nn.Module):

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

    def forward(self, input):
        output = input + 1
        return output

In [9]:
import torch

euler = MyModule()
x = torch.tensor(1.0)
output = euler(x)
output

tensor(2.)

# 卷积 Convolution Layers
![image.png](1.png)

有一个计算出错

In [11]:
import torch

input = torch.tensor([[1, 2, 0, 3, 1], [0, 1, 2, 3, 1], [1, 2, 1, 0, 0],
                      [5, 2, 3, 1, 1], [2, 1, 0, 1, 1]])

kernel = torch.tensor([[1, 2, 1], [0, 1, 0], [2, 1, 0]])

input = torch.reshape(input, (1, 1, 5, 5))
kernel = torch.reshape(kernel, (1, 1, 3, 3))
# 保证输入的尺寸相同，看官方文档

* 官方文档

![image.png](2.png)

In [12]:
output = torch.nn.functional.conv2d(input, kernel, stride=1)
output

tensor([[[[10, 12, 12],
          [18, 16, 16],
          [13,  9,  3]]]])

In [14]:
output = torch.nn.functional.conv2d(input, kernel, stride=2)
output

tensor([[[[10, 12],
          [13,  3]]]])

* padding代表上下左右各加一行，默认填充0

![3.png](3.png)

In [15]:
output = torch.nn.functional.conv2d(input, kernel, stride=1,padding=1)
output

tensor([[[[ 1,  3,  4, 10,  8],
          [ 5, 10, 12, 12,  6],
          [ 7, 18, 16, 16,  8],
          [11, 13,  9,  3,  4],
          [14, 13,  9,  7,  4]]]])